# Generated by Django 2.0.6 on 2018-07-09 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 2, 20, 27, 853876)),
        ),
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.TextField(default=None, null=True),
        ),
    ]
