# Generated by Django 2.0.6 on 2018-07-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_auto_20180709_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
