# Generated by Django 2.0.6 on 2018-07-12 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_auto_20180710_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('article', models.TextField(default=None, null=True)),
                ('author', models.TextField(default=None, null=True)),
                ('website', models.TextField(default=None, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(default=None, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Posts')),
            ],
        ),
    ]
