# Generated by Django 2.0.6 on 2018-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_posts_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
